name: Docker Image CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1    
      - uses: actions/checkout@v2
      - name: Release the Docker image
        run: make
